# Generated by Django 5.2 on 2026-04-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_candidateapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='answers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='generated_questions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='semantic_gaps',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidateapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('AWAITING_INQUIRY', 'Awaiting Inquiry'), ('EVALUATING', 'Evaluating'), ('SCORED', 'Scored'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
