# Generated by Django 5.2 on 2026-04-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_candidateapplication_answers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='employment_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='responsibilities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
