# Generated by Django 5.2 on 2026-04-28 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_jobdescription_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplication',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PARSING', 'Parsing'), ('AWAITING_INQUIRY', 'Awaiting Inquiry'), ('EVALUATING', 'Evaluating'), ('SCORED', 'Scored'), ('COMPLETED', 'Completed'), ('SHORTLISTED', 'Shortlisted'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
